name: code_union
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^5.0.1
  flutter_svg: ^1.0.3
  spider: ^4.2.1
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.7.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/svg/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope/Manrope-Bold.ttf
        - asset: assets/fonts/Manrope/Manrope-ExtraBold.ttf

        - asset: assets/fonts/Manrope/Manrope-ExtraLight.ttf
        - asset: assets/fonts/Manrope/Manrope-Light.ttf

        - asset: assets/fonts/Manrope/Manrope-Medium.ttf
        - asset: assets/fonts/Manrope/Manrope-Regular.ttf

        - asset: assets/fonts/Manrope/Manrope-SemiBold.ttf
